### ISSUE TITLE
Logo background should be the site's background

### ISSUE THREAD

**Issue by cl8n** [osu-monthly/osu-monthly.github.io#5]
the current background color is just Discord's dark theme color and it looks pretty awful

need word from the designer to see how that might work. it could be interesting to randomly place the circles and see what happens ¯\\\_(ツ)\_/¯

**Comment by jacksonisiah** [comment]
I feel like #10 voided the need for this issue currently. however this is a good basis to start with for new site.

**Comment by lvdlee** [comment]
We have a different logo meant for the website anyway, not sure why you guys used the current one. Also, the background can easily be removed from the logo, it's just there for Discord.
